# -*- coding: utf-8 -*-
"""Retail_Rocket_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Md9taR5iZnhY-YO6mvMzYC7W8wFAWXLD

## Item Selection (SQL Output)

The following 50 items were identified using SQL based on:
- High view counts  
- Low add-to-cart activity
  
This notebook analyzes these high-visibility, low-conversion items to identify where and why users fail to progress from view to action..
"""

top_50_ids=[187946,
5411,
370653,
96924,
298009,
335975,
151444,
434782,
142466,
102306,
91755,
232509,
225778,
209994,
29100,
429094,
15948,
359491,
413166,
290250,
341482,
316779,
449571,
109618,
84160,
445749,
287664,
215715,
149275,
403757,
298196,
184998,
260650,
82389,
29890,
351044,
137144,
216888,
101845,
294482,
260317,
75779,
251349,
203908,
244924,
260539,
229204,
162525,
115323,
156173]

len(top_50_ids)

from google.colab import files
files.upload()

"""Upload the dataset files required for analysis (events and item properties)."""

import pandas as pd
# df1 = pd.read_csv("item_properties_part1.csv")
# df2 = pd.read_csv("item_properties_part2.csv")
df3  = pd.read_csv("events.csv")

"""Loaded datasets:
- df1, df2 → item properties (metadata)
- df3 → user interaction events
"""

df1.shape

df3.shape

"""## Filtering Dataset for Selected Items

Extracting latest category (categoryid) for each selected item from item properties.
"""

df = pd.concat([df1, df2], ignore_index=True)

df_filtered = df1[
    (df1['property'] == 'categoryid') &
    (df1['itemid'].isin(top_50_ids))
]

df_latest = df_filtered.sort_values('timestamp').drop_duplicates(
    subset=['itemid'], keep='last'
)
df_result=df_latest[['itemid', 'property', 'value']]

print(df_result.to_string(index=False))

result_ids = set(df_latest['itemid'])

input_ids = set(top_50_ids)

missing_ids = input_ids - result_ids

print(len(missing_ids), sorted(missing_ids))

"""9 items do not have category metadata. These represent data quality issues and cannot be used for category-level analysis."""

top_9_ids=[29100, 156173, 184998, 229204, 244924, 260650, 287664, 298196, 449571]

df_all = pd.concat([df1], ignore_index=True)

check = df_all[df_all['itemid'].isin(top_9_ids)]

len(check)

"""Validation confirms that these 9 items are completely missing from item properties, reinforcing that they lack metadata."""

valid_ids = list(set(top_50_ids) - set(top_9_ids))

df_valid = df3[df3['itemid'].isin(valid_ids)]

"""Filtered dataset to 41 valid items that have category metadata.  
Subsequent analysis focuses only on these items.

## Category Level Analysis
"""

df_props = pd.concat([df1], ignore_index=True)

df_cat = df_props[
    (df_props['property'] == 'categoryid') &
    (df_props['itemid'].isin(valid_ids))
]

df_cat_latest = df_cat.sort_values(by='timestamp').drop_duplicates(
    subset=['itemid'], keep='last'
)

df_cat_latest = df_cat_latest[['itemid', 'value']].rename(
    columns={'value': 'categoryid'}
)

item_stats = df_valid.groupby(['itemid','event']).size().unstack(fill_value=0)

item_stats = item_stats.rename(columns={
    'view': 'views',
    'addtocart': 'carts',
    'transaction': 'transactions'
}).reset_index()

df_valid_cat = item_stats.merge(df_cat_latest, on='itemid', how='left')

category_stats = df_valid_cat.groupby('categoryid').agg(
    item_count=('itemid', 'count'),
    total_views=('views', 'sum'),
    total_carts=('carts', 'sum')
).reset_index()

category_stats['cart_rate'] = category_stats['total_carts'] / category_stats['total_views']

category_stats.sort_values('cart_rate')

df_cat_1188 = df_valid_cat[df_valid_cat['categoryid'] == 1188]
df_cat_1188

category_stats = df_valid_cat.groupby('categoryid').agg(
    item_count=('itemid', 'count'),
    total_views=('views', 'sum'),
    total_carts=('carts', 'sum')
).reset_index()

category_stats['cart_rate'] = category_stats['total_carts'] / category_stats['total_views']

category_stats = category_stats.sort_values('cart_rate')
print(category_stats.to_string(index=False))

broken = category_stats[category_stats['cart_rate'] == 0]

weak = category_stats[
    (category_stats['cart_rate'] > 0) &
    (category_stats['cart_rate'] < 0.005)
]

best = category_stats[category_stats['cart_rate'] >= 0.005]

broken[broken['item_count'] >= 2]

total_views = category_stats['total_views'].sum()
broken_views = broken['total_views'].sum()

impact = broken_views / total_views

print(round(impact,4))

best.sort_values('cart_rate', ascending=False)

print(category_stats['cart_rate'].describe())

q75 = category_stats['cart_rate'].quantile(0.75)
q50 = category_stats['cart_rate'].quantile(0.50)

high = category_stats[category_stats['cart_rate'] >= q75]
mid  = category_stats[(category_stats['cart_rate'] >= q50) & (category_stats['cart_rate'] < q75)]
low  = category_stats[category_stats['cart_rate'] < q50]

top_categories = category_stats.sort_values('cart_rate', ascending=False).head(5)

top_categories

"""These represent the highest-performing categories within a generally low-conversion environment.
Even the best categories show very low conversion rates, reinforcing that the issue is systemic rather than isolated.

##User Level Analysis
"""

df_ui = df3[df3['itemid'].isin(valid_ids)]

user_item = df_ui.groupby(['visitorid', 'itemid', 'event']).size().unstack(fill_value=0).reset_index()

user_item = user_item.rename(columns={
    'view': 'views',
    'addtocart': 'carts',
    'transaction': 'transactions'
})

for col in ['views', 'carts', 'transactions']:
    if col not in user_item:
        user_item[col] = 0

repeat_view = user_item[user_item['views'] >= 3]
len(repeat_view)

# never add to cart
no_cart = user_item[user_item['carts'] == 0]

# repeat viewers with no cart
high_intent_no_action = user_item[
    (user_item['views'] >= 3) & (user_item['carts'] == 0)
]

# converters
converters = user_item[user_item['carts'] > 0]

len(user_item), len(no_cart), len(high_intent_no_action), len(converters)

"""The majority of user-item interactions do not progress beyond viewing.  
A very small fraction converts, and only a limited subset shows repeated engagement without action.
"""

ratio = len(high_intent_no_action) / len(user_item)

f"{ratio:.2%}"

"""Only a small proportion of users repeatedly view items without taking action, indicating that delayed decision-making or price-waiting behavior is not a primary driver of low conversion."""

df_ui['timestamp'] = pd.to_datetime(df_ui['timestamp'], unit='ms')

time_span = df_ui.groupby(['visitorid','itemid'])['timestamp'].agg(['min','max'])

time_span['days_diff'] = (time_span['max'] - time_span['min']).dt.days

time_span['days_diff'].describe()

repeat_long_gap = time_span[time_span['days_diff'] >= 3].reset_index()

merged = repeat_long_gap.merge(user_item, on=['visitorid','itemid'])

waiting_users = merged[merged['carts'] == 0]

len(waiting_users)

zero_conversion = item_stats[
    (item_stats['views'] > 0) &
    (item_stats['carts'] == 0)
]
len(zero_conversion)

threshold = item_stats['views'].quantile(0.95)

high_view_zero = zero_conversion[
    zero_conversion['views'] >= threshold
]

high_view_zero = high_view_zero.sort_values(by='views', ascending=False)

high_view_zero

"""These are extreme failure cases where items receive high visibility but generate zero user action, representing the strongest contributors to conversion loss."""

threshold = item_stats['views'].quantile(0.90)

# Calculate cart_rate for item_stats
item_stats['cart_rate'] = item_stats['carts'] / item_stats['views']
item_stats['cart_rate'] = item_stats['cart_rate'].fillna(0) # Handle potential division by zero

problem_items = item_stats[
    (item_stats['views'] >= threshold) &
    (item_stats['cart_rate'] < 0.005)
]

problem_items.sort_values('views', ascending=False)

"""These items receive high user attention but show near-zero conversion, indicating a breakdown at the evaluation stage rather than lack of demand."""

df3[df3['itemid'] == 370653]['event'].value_counts()

df3[df3['itemid'] == 84160]['event'].value_counts()

"""Comparison shows that some items trigger user actions while others receive only views, confirming that conversion depends on crossing a decision threshold rather than traffic volume."""

problem_categories = category_stats[category_stats['cart_rate'] < 0.005]

print("Distribution of item counts per category:")
print(category_stats['item_count'].value_counts().sort_index())

items_with_categoryid = set(df_cat_latest['itemid'])
valid_items_without_categoryid = set(valid_ids) - items_with_categoryid

print(f"Items in valid_ids that DO NOT have a categoryid ({len(valid_items_without_categoryid)} items):")
print(sorted(list(valid_items_without_categoryid)))

"""These are the 19 items that are part of our `valid_ids` but do not have a `categoryid` property recorded in the `item_properties` dataset. This is why they are excluded from the category-level performance analysis, even though they are considered 'valid' in other contexts.

# Visualization

### Overall Conversion Funnel
"""

total_views_overall = df3[df3['event'] == 'view'].shape[0]
total_carts_overall = df3[df3['event'] == 'addtocart'].shape[0]
total_transactions_overall = df3[df3['event'] == 'transaction'].shape[0]

stages_overall = ['View (Overall)', 'AddToCart (Overall)', 'Transaction (Overall)']
values_overall = [total_views_overall, total_carts_overall, total_transactions_overall]

plt.figure()
bars_overall = plt.bar(stages_overall, values_overall)
plt.title("Overall Conversion Funnel (All Events)")
plt.ylabel("Users")

# Add labels to the bars
for bar in bars_overall:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.05, round(yval, 2), ha='center', va='bottom')

plt.show()

"""The funnel shows a sharp drop from View to AddToCart, indicating that the primary conversion failure occurs at the first decision stage.

While a significant number of users view items, only a very small fraction proceed to add them to cart, confirming that the issue lies in converting interest into action rather than driving traffic.

Views vs Cart Rate
"""

plt.figure()
plt.scatter(item_stats['views'], item_stats['cart_rate'])
plt.xlabel("Views")
plt.ylabel("Cart Rate")
plt.title("Views vs Conversion")
plt.show()

"""The scatter plot shows that items with high views are concentrated near zero conversion rates.

This indicates that increased visibility does not lead to higher conversion, confirming that the issue lies in the product evaluation stage rather than user interest or traffic.

A large cluster of high-view items with near-zero conversion highlights systemic inefficiency in converting user attention into action.

Category-Level Performance
"""

plt.figure()
plt.bar(category_stats['categoryid'].astype(str), category_stats['cart_rate'])
plt.xticks(rotation=90)
plt.title("Category Conversion Rates")
plt.ylabel("Cart Rate")
plt.show()

"""Most categories show near-zero conversion rates, with only a few categories exhibiting slightly higher performance.

This indicates that conversion failure is not isolated to specific items but is clustered at the category level, suggesting broader issues in product presentation or category-level user experience.

Even the highest-performing categories remain significantly below typical conversion benchmarks, reinforcing that the problem is systemic rather than localized.

Distribution of Cart Rate
"""

plt.figure()
plt.hist(item_stats['cart_rate'], bins=50)
plt.title("Cart Rate Distribution")
plt.xlabel("Cart Rate")
plt.ylabel("Frequency")
plt.show()

"""The distribution is heavily concentrated near zero, indicating that the majority of items have extremely low or no conversion.

This confirms that poor conversion is not limited to a few outliers but is widespread across most items.

Only a very small number of items achieve even marginal conversion, highlighting a systemic inability to convert user interest into action.

Top failure items
"""

top_fail = item_stats.sort_values('views', ascending=False).head(20)

plt.figure()
plt.bar(top_fail['itemid'].astype(str), top_fail['views'])
plt.xticks(rotation=90)
plt.title("Top Viewed Items")
plt.show()

"""These items attract the highest user attention, yet many of them exhibit little to no conversion.

This highlights that high visibility alone does not translate into user action, reinforcing the gap between interest and purchase intent.

Several of these high-traffic items belong to the previously identified low-conversion segment, showing that they disproportionately contribute to the overall conversion drop.

## Final Conclusion

- The primary drop in the funnel occurs at the View → AddToCart stage, not at later steps.

- High user activity (views) does not translate into action, indicating a failure in converting interest into intent.

- A significant portion of traffic is concentrated on items with near-zero conversion, which disproportionately lowers overall performance.

- Conversion failure is not isolated to individual products but is clustered at the category level, suggesting systemic issues.

- User behavior shows that most users do not revisit or reconsider items, confirming that the failure occurs at the first interaction rather than during delayed decision-making.

- Items with missing metadata further contribute to zero conversion, highlighting data quality issues.

### Final Insight

Users are willing to explore products, but most items fail to cross the minimum decision threshold required to trigger action, leading to immediate drop-off and low overall conversion.
"""